stages:
  - test
  - build
  - deploy

variables:
  DOCKER_TLS_CERTDIR: ""

test:
  stage: test
  image: python:3.12-slim
  script:
    - pip install -r app/requirements.txt
    - python -c "import flask, docker; print('All imports OK')"

build:
  stage: build
  image: docker:24
  services:
    - name: docker:24-dind
      alias: docker
  script:
    - docker build -t devops-dashboard:$CI_COMMIT_SHORT_SHA .
    - echo "Build successful"

deploy:
  stage: deploy
  image: alpine:latest
  script:
    - echo "Deploy stage - OK"
